let books = [
  {
    id: 1,
    titre: "Fourth Wing (The Empyrean, 1)",
    annee_edition: 1945,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_pages: 528,
  },
  {
    id: 2,
    titre: "Fourth Wing (The Empyrean, 2)",
    annee_edition: 1947,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_pages: 600,
  },
  {
    id: 3,
    titre: "Fourth Wing (The Empyrean, 3)",
    annee_edition: 1949,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_pages: 455,
  },
  {
    id: 4,
    titre: "Fourth Wing (The Empyrean, 4)",
    annee_edition: 1951,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_pages: 789,
  },
  {
    id: 5,
    titre: "Fourth Wing (The Empyrean, 5)",
    annee_edition: 1999,
    lien_image: "lien-Image",
    lien_pdf: "lien-Image",
    resume: "Petit résumé du livre",
    editeur: "Rebecca Yarros",
    nombre_de_pages: 512,
  },
];

export { books };
